### ISSUE TITLE
Planned new features

### ISSUE THREAD

**Issue by PetriAsi** [WodongaTAFE/PSMoodle#11]
Hi, 
first thanks for this module.
I'm planning to use it  to sync cohors with  external systems.  First I have to return all cohorts from moodle. I would like  do some tuning to module code  make this little easier to implement. 

Are you willing to accept pull request if I write "return all" ie. -all switch logic for Get-MoodleCohort. There's also need for add -limitfrom and -limitnum parameters.

**Comment by mabster** [comment]
Hi @PetriAsi!

Sorry - had some time off last week so I'm just getting to this now.

I see your pull requests. I am not using the cohort functions personally so I'll have to take your word for them that they work the way you intend and won't break anyone already using them. Are you confident?

**Comment by PetriAsi** [comment]
NP at all. We all have other things to do.

I have been as careful as I could when making  changes.  I always try to look from other users perspective all code and feature I wrote.  So I'm confident that I have done everything not to break anything when adding features. 

Have you any plan to include github CI/CD to MoodlePS?  Reason I ask is that  I'm maintaining couple of modules [SnipeitPS](https://github.com/snazy2000/SnipeitPS/) and [WilmaPSWorker](https://github.com/PetriAsi/WilmaPSWorker) both
are using AppVeyor for automatic testing and pushing releases to powershell gallery.  CI/CD is little work to set up, but it makes 
releasing and testing so easy.

Starting point could be just  adding development branch here for merging and testing pull requests.


(Just tagging my current PRs here #12 , #13)

**Comment by mabster** [comment]
Oh we definitely have CI/CD working. When I publish a new "release" on GitHub, a new version of the module is automatically pushed to the gallery.

**Comment by mabster** [comment]
OK I've merged your two pull requests and will publish a new version soon! Tied up in meetings this arvo so it may be tomorrow. It doesn't take long but I want to be free while it happens in case I need to resolve any issues.

**Comment by PetriAsi** [comment]
> Oh we definitely have CI/CD working. ...
That's nice to hear. Setup must be cleaner than that copied for my module. :)
