### ISSUE TITLE
Cannot find type

### ISSUE THREAD

**Issue by ghost** [WodongaTAFE/PSMoodle#14]
Hi,

Do you know what might be the issue here? Every time I am trying to use _Get-MoodleUser_, I am getting this error. 

A simmilar error shows  for commands involving cohorts for example. I know that I am properly connected as I am able to create new users using _New-MoodleUser_

![image](https://user-images.githubusercontent.com/72248197/194301538-aabe26e5-3fdf-4bf3-aecd-8bbb26048e4a.png)

**Comment by mabster** [comment]
Hi @tompivny!

I've never seen that issue with the Moodle module, but I have seen it once or twice in the past with other modules. Usually the solution was to uninstall/reinstall the module. I think it's some sort of glitch in PowerShell 5.x.

I'll leave this issue open - give uninstalling/reinstalling a try and see if it comes good. Let me know!

**Comment by mabster** [comment]
Hi again @tompivny! Haven't heard back from you so I will close this issue. Leave me a comment if you're still seeing the issue after uninstalling & reinstalling. Cheers!
