### ISSUE TITLE
Multiple new features

### ISSUE THREAD

**Issue by jonahhes** [WodongaTAFE/PSMoodle#15]
Hey @mabster 

Thank you for this module. We are going to use it in a corporate environment and needed a bunch of additional features, which I implemented:

- Communication via proxy server
- OAUTH2 as auth method for new users
- Get all cohorts globally
- Assign/unassign roles to/from users
- Find existing users based on auth method

I'm going to send you a whole bunch of pull requests with all these features hoping to improve the module for everyone.
Feel free to suggest changes or improvements!

**Comment by mabster** [comment]
Hey @jonahhes!

I've published v0.15 with your changes. I suspect we might need another release though, because I think you didn't add all your new function names to the .psd1 file. I added Find-MoodleUser but there were some role-related ones too, right?

**Comment by jonahhes** [comment]
Thanks you. I sent another pull request.
Interesting how the functions were available without being in there.

**Comment by mabster** [comment]
Rock on! I've just published 0.16 with all your changes.

Can you give 'em a whirl and, if everything's good, close this issue? Thanks so much for your contribution! It's awesome to have others contributing code to our humble module. 😊

**Comment by jonahhes** [comment]
Thank you for creating the module in the first place!
I ran our code with module version 0.16 and it all seems to work! If I need to make any more changes or fix any bugs that crop up, I'll let you know.
