### ISSUE TITLE
Error connect moodle

### ISSUE THREAD

**Issue by brillantju** [WodongaTAFE/PSMoodle#4]
Hello,

First of all thank you for this work which can help us enormously.

I encounter a small problem when I want to use the script.

I have no problem installing the "moodle" module.

On the other hand, when I want to connect to the moodle instance I have an error:

```
Invoke-RestMethod : Le serveur distant a retourné une erreur : (404) Introuvable.
Au caractère C:\Program Files\WindowsPowerShell\Modules\Moodle\0.7\public\Connect-Moodle.ps1:62 : 16
+     $result  = Invoke-RestMethod -Uri ([uri]::new($Uri, $path))
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
 
Could not connect to http://10.10.50.17/moodle with the given token.
Au caractère C:\Program Files\WindowsPowerShell\Modules\Moodle\0.7\public\Connect-Moodle.ps1:70 : 9
+         throw "Could not connect to $Uri with the given token."
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not conne...he given token.:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not connect to http://10.10.50.17/moodle with the given token.
```
 
 
 

It works fine when I use:

`http://10.10.50.17/moodle/webservice/rest/server.php?wstoken=XXXX&wsfunction=core_webservice_get_site_info&moodlewsrestformat=json`

`{"sitename":"Test Julien","username":"apiweb","firstname":"api","lastname":"web","fullname":"api web","lang":"fr","userid":4,"siteurl":"http:\/\/10.10.50.17\/moodle","userpictureurl":"http:\/\/10.10.50.17\/moodle\/theme\/image.php\/boost\/core\/1600691171\/u\/f1","functions":[{"name":"core_webservice_get_site_info","version":"2020061501"},{"name":"auth_email_get_signup_settings","version":"2020061500"},{"name":"core_auth_confirm_user","version":"2020061501"}],"downloadfiles":0,"uploadfiles":0,"release":"3.9.1 (Build: 20200713)","version":"2020061501","mobilecssurl":"","advancedfeatures":[{"name":"usecomments","value":1},{"name":"usetags","value":1},{"name":"enablenotes","value":1},{"name":"messaging","value":1},{"name":"enableblogs","value":1},{"name":"enablecompletion","value":1},{"name":"enablebadges","value":1},{"name":"messagingallusers","value":0},{"name":"mnet_dispatcher_mode","value":0}],"usercanmanageownfiles":true,"userquota":104857600,"usermaxuploadfilesize":33554432,"userhomepage":1,"userprivateaccesskey":"df10d3059cf0f044a62442acdfa7b83c","siteid":1,"sitecalendartype":"gregorian","usercalendartype":"gregorian","userissiteadmin":false,"theme":"boost"}`

thank you

**Comment by mabster** [comment]
Hi brilliantju!

It might be something to do with the fact that your Moodle instance lives under a /moodle folder on your server.

Can you try specifying a URL with a trailing slash in your Connect-Moodle call?

So instead of:

    Connect-Moodle -Uri http://10.10.50.17/moodle -Token ...

... try:

    Connect-Moodle -Uri http://10.10.50.17/moodle/ -Token ...

Let me know if that works!

**Comment by mabster** [comment]
Hmm, no, that doesn't help.

I don't think I expected a Moodle instance to be hosted somewhere other than the root. I will need to make some changes to fix this. Stay tuned!

**Comment by mabster** [comment]
Ok, update to version 0.8 and try again! Let me know if this solves your issue.

You will still need to include a trailing slash in your URI. Like this:

    Connect-Moodle -Uri http://10.10.50.17/moodle/ -Token ...

**Comment by brillantju** [comment]
Hello Mabster,

Thank you for your answer
It's better. But I have a new error.

```
PS C:\Windows\system32> C:\Users\jbrillant\Desktop\test_moodle.ps1
Connected to Test Julien as user apiweb.
Impossible d’appeler une méthode dans une expression Null.
Au caractère C:\Users\jbrillant\Desktop\test_moodle.ps1:12 : 9
+         $PsCmdlet.SessionState.PSVariable.Set("_MoodleUrl", $Url)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Impossible d’appeler une méthode dans une expression Null.
Au caractère C:\Users\jbrillant\Desktop\test_moodle.ps1:13 : 9
+         $PsCmdlet.SessionState.PSVariable.Set("_MoodleToken", $Token)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```


I will see to modify the url to access moodle so that it is at the root.

Thank you

**Comment by mabster** [comment]
Can you show me the command you're running inside your "test_moodle.ps1" script?

**Comment by mabster** [comment]
It kinda looks like you have an old copy of the Module. I can see a line there referencing $Url, but we use $Uri in the newest versions of the module. Double check that you only have version 0.8 installed by typing:

    Get-Module Moodle -List

**Comment by brillantju** [comment]
It's fine !
The connexion it's OK.

```
PS C:\Windows\system32> Get-Module Moodle -List


    Répertoire : C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands                                                                     
---------- -------    ----                                ----------------                                                                     
Script     0.8        Moodle                              {Add-MoodleCohortMember, Connect-Moodle, Copy-MoodleCourse, Disconnect-Moodle...}   
``` 

But i am sorry.

I have a little problem..


When I want to test the order

`Get-MoodleUser -UserName 'dupond' | Set-MoodleUser -Suspended $true`

I have the following error.

```
Set-MoodleUser : Exception du contrôle d'accès
Au caractère Ligne:1 : 37
+ Get-MoodleUser -UserName 'dupond' | Set-MoodleUser -Suspended $true
+                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Set-MoodleUser
```

Thank you

**Comment by mabster** [comment]
Ok so that's Moodle permissions. The account you are connecting to your Moodle instance with does not have permission to modify users. Does that make sense? I don't know enough about Moodle administration to help you fix that.

**Comment by brillantju** [comment]
OK, I'll take a look at the rights.
The user has the role: "manager"

Thank-you for your prompt response.

**Comment by mabster** [comment]
Ok I'm gonna close this issue 'coz the original problem of not working with Moodle instances not in the root is now fixed. Thanks for helping me find that bug! Feel free to open a new issue if you still have problems!
