### ISSUE TITLE
Addition of Remove-MoodleUser

### ISSUE THREAD

**Issue by pawelpvl** [WodongaTAFE/PSMoodle#5]
Hi,

What do you think about adding the "Remove-MoodleUser" cmdlet that would use the function "core_user_delete_users"?

**Comment by mabster** [comment]
I'm not against it! Would you like to have a crack at it yourself, or would you like me to add it?

**Comment by pawelpvl** [comment]
It would be great if you added it. I'd like to add it on my own, but my PS scripting skills are not so advanced yet (working on it :)).

**Comment by mabster** [comment]
OK version 0.9 is publishing now, with Remove-MoodleUser! Give it a try and let me know how you go!

**Comment by pawelpvl** [comment]
Thank you, Matt! Much appreciated.

**Comment by pawelpvl** [comment]
Works like a charm. Thank you!

**Comment by mabster** [comment]
Awesome! I'll close this issue then.
