### ISSUE TITLE
Add OIDC to Authentication Method Selection Set

### ISSUE THREAD

**Issue by steadhouse** [WodongaTAFE/PSMoodle#6]
In New-MoodleUser, would it be possible to add OIDC for OpenIDConnect authentication to the validation selection on line 47?

Thank you!

**Comment by mabster** [comment]
Easy fix! Are there any other values for "auth" that might make sense to add while I'm at it? I don't think the possible values are documented anywhere.

**Comment by mabster** [comment]
OK just published version 0.11 with OIDC as an option in New-MoodleUser and Set-MoodleUser! Leave me a comment here if it works for you so we can close this issue. Thanks!

**Comment by steadhouse** [comment]
Awesome!

I’ve been digging around looking for other value options and couldn’t find any. I’ll test the news version!

Thanks,

-- Stead Halstead

**Comment by steadhouse** [comment]
@mabster Updated, tested, and worked flawlessly! Issue can be closed - thanks for the quick action!
