### ISSUE TITLE
Azure synchronized accounts

### ISSUE THREAD

**Issue by KrisVG-CRS** [WodongaTAFE/PSMoodle#7]
Is it by design that functions like Get-MoodleUser, Get-MoodleEnrolledUser, ... only work for accounts that were defined in Moodle and not for accounts that were synchronized to Moodle from an Azure AD or am I missing something?

**Comment by mabster** [comment]
Ah we don't use the Azure sync Moodle plug-in so I wasn't aware that the behaviour would be any different for those users!

Does that mean the built-in Moodle web services for users don't return users synced from Azure AD? We're not doing anything fancy in those cmdlets - just calling the Moodle web services.

Does Get-MoodleUser throw an error for you? Or does it just not return any users?

**Comment by KrisVG-CRS** [comment]
No errors, nothing is returned. I already suspected something was wrong when the Connect-Moodle function only worked with accounts defined in Moodle (i.e. not synched from Azure).

**Comment by mabster** [comment]
OK I'm not sure there's much we can do about it from here, but can I suggest posting on the official Moodle forums and seeing if others who use the Azure AD sync have seen the same behaviour? Post a link to your thread in here and I'll keep an eye on it in case it ends up being something I can fix!

**Comment by KrisVG-CRS** [comment]
OK, I'll try that. Thanks for the quick response.

**Comment by mabster** [comment]
Link to discussion in case there's something we can fix in the scripts:

https://moodle.org/mod/forum/discuss.php?d=428284

**Comment by mabster** [comment]
Doesn't seem like your post is getting much traction. Have you found a workaround in the meantime?

**Comment by KrisVG-CRS** [comment]
No, we've accepted that the Moodle module isn't going to work for us.
Since we weren't really impressed with the "Moodle Sync from Azure" implementation either we might consider abandoning that and opting for the Moodle module to create accounts and courses. But at the earliest that will be something for september next year (our school years start in september).

**Comment by mabster** [comment]
OK, I'll close this one for now. But - if/when you are looking at this module again, hit me up! I'll be happy to share the scripts we're using to provision users and enrol them in the appropriate course(s).
