### ISSUE TITLE
Add users to group

### ISSUE THREAD

**Issue by RolliMK** [WodongaTAFE/PSMoodle#8]
Hey, 
I have recently discovered this little gem and it´s exactly what I needed to connect an external student tracking website with Moodle. The only issue I´m having is user enrolment into groups. I can see that creation/updating of groups is possible, but there is no user enrolment into groups? or am I missing something. Hope you can point me in the right direction and happy new year :)

**Comment by mabster** [comment]
I'm not back at work until next week, RolliMK, but I will do some reading in the meantime so I can get this added for you. Shouldn't be a big deal if the web services support it.

**Comment by mabster** [comment]
Just published v0.12 with Add-MoodleGroupMember and Remove-MoodleGroupMember!

I've given it a cursory test and both functions appear to work, feel free to reopen this issue or make a new one if anything goes awry!
